// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOoAVWX93g1IAtgtKJGVzru3P94gIEo2s',
    appId: '1:998550223677:web:ee2a1ed4b3821cd8736354',
    messagingSenderId: '998550223677',
    projectId: 'lg-dx-school-6-1',
    authDomain: 'lg-dx-school-6-1.firebaseapp.com',
    databaseURL: 'https://lg-dx-school-6-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-6-1.firebasestorage.app',
    measurementId: 'G-XK6E23FLLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVEsxnU3oZxsI_RznpaZUiVZfBhvF6PE',
    appId: '1:998550223677:android:82846cca833e4d17736354',
    messagingSenderId: '998550223677',
    projectId: 'lg-dx-school-6-1',
    databaseURL: 'https://lg-dx-school-6-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-6-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjLglKnbzantpTRm0WyMN58Mr_vZleUw',
    appId: '1:998550223677:ios:7c8b7d408a329355736354',
    messagingSenderId: '998550223677',
    projectId: 'lg-dx-school-6-1',
    databaseURL: 'https://lg-dx-school-6-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-6-1.firebasestorage.app',
    iosBundleId: 'com.lgdxschool.instagram',
  );

}