// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ua8my7DLW-lreLvdvjKnHKIHcTkOny0',
    appId: '1:171658422182:web:deb4772d3c55e1a56b5167',
    messagingSenderId: '171658422182',
    projectId: 'lg-dx-school-2-2',
    authDomain: 'lg-dx-school-2-2.firebaseapp.com',
    databaseURL: 'https://lg-dx-school-2-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-2-2.firebasestorage.app',
    measurementId: 'G-RPMZNTFSZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRESl8UXJu8uxTMGRxuRJUZ7SO7ElEONw',
    appId: '1:171658422182:android:eba9f58801cd91fb6b5167',
    messagingSenderId: '171658422182',
    projectId: 'lg-dx-school-2-2',
    databaseURL: 'https://lg-dx-school-2-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-2-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDspZ148weAuEJ7-3RDJbWaJ33LVhV-rIc',
    appId: '1:171658422182:ios:3bc0c028fc417b346b5167',
    messagingSenderId: '171658422182',
    projectId: 'lg-dx-school-2-2',
    databaseURL: 'https://lg-dx-school-2-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lg-dx-school-2-2.firebasestorage.app',
    iosBundleId: 'com.lgdxschool.instagram',
  );
}
